# dvc.yaml

stages:
  prepare:
    cmd: python src/data/make_dataset.py
    deps:
      - src/data/make_dataset.py
      - data/raw/UCI_Credit_Card.csv
    outs:
      - data/processed/train.csv
      - data/processed/test.csv

  validate:
    cmd: python src/data/run_validation.py
    deps:
      - src/data/run_validation.py
      - data/processed/train.csv
      - great_expectations/expectations/credit_data_suite.json

  train:
    cmd: python src/models/train.py
    deps:
      - src/models/train.py
      - src/models/pipeline.py
      - data/processed/train.csv
    outs:
      - models/credit_default_model.pkl
    metrics:
      - metrics.json:
          cache: false